backend:
  name: git-gateway
  branch: main # Your default branch name

media_folder: "assets/images/uploads" # Where uploaded images will go
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "_data/home.yml"
        fields:
          - { name: "title", label: "Site Title", widget: "string" }
          
          # Hero Section
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { name: "heading", label: "Heading", widget: "string" }
              - { name: "subheading", label: "Subheading", widget: "text" }
              - { name: "primary_cta", label: "Primary Button Text", widget: "string" }
              - { name: "secondary_cta", label: "Secondary Button Text", widget: "string" }
              - { name: "background_images", label: "Background Images", widget: "list", field: { name: "image", label: "Image", widget: "image" } }
          
          # Services Section
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - { name: "heading", label: "Section Heading", widget: "string" }
              - { name: "description", label: "Section Description", widget: "text" }
              - label: "Services"
                name: "items"
                widget: "list"
                fields:
                  - { name: "title", label: "Service Title", widget: "string" }
                  - { name: "description", label: "Description", widget: "text" }
                  - { name: "icon", label: "Icon Class (Font Awesome)", widget: "string" }
                  - { name: "image", label: "Service Image", widget: "image" }
                  - { name: "button_text", label: "Button Text", widget: "string" }
          
          # Testimonials Section
          - label: "Testimonials Section"
            name: "testimonials"
            widget: "object"
            fields:
              - { name: "heading", label: "Section Heading", widget: "string" }
              - { name: "description", label: "Section Description", widget: "text" }
              - label: "Testimonials"
                name: "items"
                widget: "list"
                fields:
                  - { name: "quote", label: "Testimonial Text", widget: "text" }
                  - { name: "name", label: "Client Name", widget: "string" }
                  - { name: "position", label: "Client Position", widget: "string" }
                  - { name: "image", label: "Client Photo", widget: "image" }
          
          # Work With Us Section
          - label: "Work With Us Section"
            name: "work"
            widget: "object"
            fields:
              - { name: "heading", label: "Section Heading", widget: "string" }
              - { name: "description", label: "Section Description", widget: "text" }
              - label: "Benefits"
                name: "benefits"
                widget: "list"
                fields:
                  - { name: "title", label: "Benefit Title", widget: "string" }
                  - { name: "description", label: "Benefit Description", widget: "text" }
                  - { name: "icon", label: "Icon Class (Font Awesome)", widget: "string" }